---
- hosts: qaserver
  become: yes
  ignore_errors: yes
  tasks:
    - name: Intall package
      package:
        name: "{{ item }}"
        state: present
        with_items:
          - unzip
          - wget
          - httpd
    - name: download
         shell 
